version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: gerenciador-tarefas-db
    environment:
      POSTGRES_USER: seu_usuario
      POSTGRES_PASSWORD: sua_senha
      POSTGRES_DB: gerenciador_tarefas
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    build: .
    container_name: gerenciador-tarefas-api
    depends_on:
      - postgres-db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/gerenciador_tarefas
      SPRING_DATASOURCE_USERNAME: seu_usuario
      SPRING_DATASOURCE_PASSWORD: sua_senha
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge